name: charity_bridge
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  firebase_core: ^3.15.0
  cloud_firestore: ^5.6.10
  firebase_storage: ^12.4.8
  shared_preferences: ^2.2.3

# ... rest of your file
