name: charity_bridge
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter packages
  cupertino_icons: ^1.0.8

  # Firebase core packages
  http: ^0.13.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_app_check: ^0.2.1+14
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2
  location: ^8.0.1
  google_maps_flutter: ^2.2.3
  google_maps_flutter_web: ^0.5.12+2
  google_maps_webservice: any
  flutter_google_places: ^0.3.0

  universal_html: ^2.2.4

  google_api_headers: 1.6.0

  # App features
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  image_picker: ^1.1.2
  fl_chart: ^1.0.0
  intl: ^0.20.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/icon/