// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2vwjFCSdhza-SEFEEY5MRbIWsiXNWzSA',
    appId: '1:191514245242:web:c6dc8d3255704868d0a3c3',
    messagingSenderId: '191514245242',
    projectId: 'donationapp-3c',
    authDomain: 'donationapp-3c.firebaseapp.com',
    storageBucket: 'donationapp-3c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Nn7DgtvRqMMONgpy6MtpE2gPmvt5h1g',
    appId: '1:191514245242:android:7def094ed9404baad0a3c3',
    messagingSenderId: '191514245242',
    projectId: 'donationapp-3c',
    storageBucket: 'donationapp-3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkTXoH2llvyJp5VhC5N2c8zJgqkXCAgn0',
    appId: '1:191514245242:ios:ec4f55422dfc82d5d0a3c3',
    messagingSenderId: '191514245242',
    projectId: 'donationapp-3c',
    storageBucket: 'donationapp-3c.firebasestorage.app',
    iosClientId: '191514245242-pl42tovl42p7ts67ptfklh3b9gatbh78.apps.googleusercontent.com',
    iosBundleId: 'com.example.donationappFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkTXoH2llvyJp5VhC5N2c8zJgqkXCAgn0',
    appId: '1:191514245242:ios:ec4f55422dfc82d5d0a3c3',
    messagingSenderId: '191514245242',
    projectId: 'donationapp-3c',
    storageBucket: 'donationapp-3c.firebasestorage.app',
    iosClientId: '191514245242-pl42tovl42p7ts67ptfklh3b9gatbh78.apps.googleusercontent.com',
    iosBundleId: 'com.example.donationappFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2vwjFCSdhza-SEFEEY5MRbIWsiXNWzSA',
    appId: '1:191514245242:web:fb830ce00ae06e2ed0a3c3',
    messagingSenderId: '191514245242',
    projectId: 'donationapp-3c',
    authDomain: 'donationapp-3c.firebaseapp.com',
    storageBucket: 'donationapp-3c.firebasestorage.app',
  );

}